### ISSUE TITLE
Screen scroll down then start the couter.

### ISSUE THREAD

**Issue by 02harleen** [izupet/angular2-counto#13]
Hi, Start the counter on the screen down. Please tell us how to possible?

**Comment by izupet** [comment]
You mean you want to start counting animation when scrolled to some position? You need to implement some kind of scroll spy (many libraries are already available or make your own) and when your counter is in viewpoint you just update on of the counto directive parameters to run/rerun the animation. Every time you change one of the parameters, animation will perform.
