### ISSUE TITLE
Build --aot error

### ISSUE THREAD

**Issue by ivanguimam** [izupet/angular2-counto#18]
I am trying to compile --aot and am getting this error

Command run: ng build -e production -prod --aot

`ERROR in : Unexpected value 'CountoModule in /home/ivan/repositories/alluagro/pro/alluagro-pro-frontend/node_modules/angular2-counto/src/counto.module.d.ts' imported by the module 'AdminModule in /home/ivan/repositories/alluagro/pro/alluagro-pro-frontend/src/app/admin/admin.module.ts'. Please add a @NgModule annotation.`

**Comment by izupet** [comment]
Will give it a look today.

**Comment by pantonis** [comment]
Have the same problem here.

**Comment by ivanguimam** [comment]
The problem still exists

Angular CLI: 1.5.3
Node: 8.9.1
OS: linux x64
Angular: 5.1.3

**Comment by izupet** [comment]
Should be fixed now.

**Comment by ivanguimam** [comment]
thanks +1 star

**Comment by pantonis** [comment]
Confirm that is working now!
