### ISSUE TITLE
Not working with Angular 6.0.3

### ISSUE THREAD

**Issue by navcoder6** [izupet/angular2-counto#21]
I have installed using npm and imported the "CountoModule" in app.module.ts. But still on running browser is giving error : -
Can't bind to 'step' since it isn't a known property of 'div'. ("              <span class="group-alarm-tile-text">True Alarms Count</span> 
            <div counto [ERROR ->][step]="30" [countTo]="10" [countFrom]="0" [duration]="4" class="true-alarm-color group-alarm-tile-co"):

**Comment by izupet** [comment]
Looks like you didn't import it right.. Not enough info to help you more.

**Comment by navcoder6** [comment]
Yeah it was something to do with the module structure that I had. I has to import it another module rather than app.module.
Closing this issue.
