### ISSUE TITLE
Can this directive work with dynamic values rather than hard coded values.

### ISSUE THREAD

**Issue by navcoder6** [izupet/angular2-counto#22]
The place where I am using this directive shows a count of messages that is dynamically calculated based on the number returned from back-end API. So instead of [countFrom] and [countTo] hardcoded in html. 
Can I set them such that whenever count changes from a number to another UI increases or decreases the number in animated form?

**Comment by izupet** [comment]
Of course. You can apply variables from component to [countFrom] and [countTo] events.
 
simple example:
[countTo]="numberOfMessagesFromAPI"

in component: numberOfMessagesFromAPI = 10;

**Comment by navcoder6** [comment]
I did it but it doesn't seem to work. Will it be possible for you to share a working demo for the same on Stackblitz or Codepen?

**Comment by izupet** [comment]
You have an example in gh-pages branch.

**Comment by navcoder6** [comment]
Got it working. Thanks :)
