### ISSUE TITLE
Rounding errors during interval count

### ISSUE THREAD

**Issue by japalo** [izupet/angular2-counto#4]
Hi,
I've found that in some cases the emitted value has got a lot of decimals. I suggest that in the directive where the emit is done the value should be rounded closest integer while counting. In the end of the count the directive can pass `_this._countTo` as intended with or without decimals.

What do you think?

**Comment by izupet** [comment]
I will take a look on that. You can create PR if you want to speed up things.

**Comment by izupet** [comment]
You should handle rounding with pipes or custom methods.
