### ISSUE TITLE
Unable to use your module in Ionic 2

### ISSUE THREAD

**Issue by dacodemaniak** [izupet/angular2-counto#6]
Hello,
Would like to use your module in an Ionic 2 app but, after install it, and build Android.... get an ENONENT error

[21:42:49]  ionic-app-script task: "build"
[21:42:49]  Error: ./~/angular2-counto/src/counto.directive.ts Module build failed: Error: ENOENT: no such file or
            directory, open 'C:\devspace\Apps\Ionic\EasyStock\node_modules\angular2-counto\src\counto.directive.js' at
            Error (native) @ ./~/angular2-counto/index.js 2:25-58 @ ./src/app/app.module.ts @
            ./src/app/main.ts,./~/angular2-counto/src/counto.module.ts Module build failed: Error: ENOENT: no such file
            or directory, open 'C:\devspace\Apps\Ionic\EasyStock\node_modules\angular2-counto\src\counto.module.js' at
            Error (native) @ ./~/angular2-counto/index.js 4:22-52 @ ./src/app/app.module.ts @ ./src/app/main.ts
Error: ./~/angular2-counto/src/counto.directive.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\devspace\Apps\Ionic\EasyStock\node_modules\angular2-counto\src\counto.directi
ve.js'
    at Error (native)
 @ ./~/angular2-counto/index.js 2:25-58
 @ ./src/app/app.module.ts

Wonder why "js" are used instead "ts" and don't understand this kind of error...

Thx 4 help

JL

**Comment by izupet** [comment]
Hi, I am not quite familiar with Ionic so I really can't help you out here...

**Comment by dacodemaniak** [comment]
No problem, thx 4 help...
Will try to do an other way...
