### ISSUE TITLE
multiple elements in the same page malfunctioning

### ISSUE THREAD

**Issue by ebicoglu** [izupet/angular2-counto#8]
when you put 2 counto elements on the same html then both counts up to the same value. i guess because of a static variable

**Comment by izupet** [comment]
You should use multiple counto directives like this (each countoChange event value should be set to different variable):

`<div counto [step]="30" [countTo]="10" [countFrom]="0" [duration]="3" (countoChange)="a = $event">{{a}}</div><div counto [step]="30" [countTo]="20" [countFrom]="0" [duration]="10" (countoChange)="b = $event">{{b}}</div>`

**Comment by ebicoglu** [comment]
Thanks. working now :)
