### ISSUE TITLE
Sometime it doesn't recognize counto directive

### ISSUE THREAD

**Issue by kolgate1001** [izupet/angular2-counto#9]
Hi,
I found that sometime it doesn't recognize couto directive. I follow your instruction and it show an error:

Unhandled Promise rejection: Template parse errors:
Can't bind to 'step' since it isn't a known property of 'div'. ("              <div>Total Hours</div>
                        <div counto [ERROR ->][step]="30" [countTo]="10" [countFrom]="0" [duration]="4" (countoChange)="intermediate = $event" (cou")

**Comment by izupet** [comment]
It looks like you did't add counto directive to your div or you did't import it right. You should show more code to help you out...

**Comment by klearchos** [comment]
Hi,

I am using angluar-cli and when I build with -aot I receive the following message:
ERROR in ng:///.../src/app/app.component.html (23,35): Property 'counto' does not exist on type 'AppComponent'.

If I build the app without the -aot flag everything are ok.
@kolgate1001 have you noticed something similar?

**Comment by kolgate1001** [comment]
Hi guys,

I just found that if I have child module, so I need to set reference from this child module to couto directive. 
In my case: I have 

--- root module
------child module
---------child component (which use couto directive)

So if I want to use couto directive in child component, I need to import CountoModule from child module (not root module).

Issue resolved.

Thank you guys.

**Comment by jgpacheco** [comment]
@klearchos Same issue for me using --aot flag. You should open a new issue with your description.

**Comment by mattiacolleoni** [comment]
> Hi guys,
> 
> I just found that if I have child module, so I need to set reference from this child module to couto directive.
> In my case: I have
> 
> --- root module
> ------child module
> ---------child component (which use couto directive)
> 
> So if I want to use couto directive in child component, I need to import CountoModule from child module (not root module).
> 
> Issue resolved.
> 
> Thank you guys.

This doesn't resolve the issue for me. Wherever I import the CountModule, using
`ng build --prod`
I obtain the following message:
`Property 'counto' does not exist on type etc...`
